quilometro = float (input("Por gentileza informar uma distancia em quilometros: "))

hectometros = float (quilometro*10)
decametros  = float (quilometro*100)
metros      = float (quilometro*1000)
centimetros = float (quilometro*100000)
milimetros  = float (quilometro*1000000)

print ("hectometros: "+str(hectometros))
print ("decametros: "+str(decametros))
print ("metros: "+str(metros))
print ("centimetros: "+str(centimetros))
print ("milimetros: "+str(milimetros))