dinheiroConta = float(input("Por gentileza informar quanto de dinheiro uma pessoa tem na conta: "))

primeiraCompra = float(input("Por gentileza informar o valor da primeira compra: "))

segundaCompra = float(input("Por gentileza informar o valor da segunda compra: "))

calculoCompra = float (primeiraCompra+segundaCompra)

if (dinheiroConta>calculoCompra):
   print("verdadeiro") 
else:
   print("falso")



