print("Qual série você assistiu no final de semana?")
print("[1] Sandman")
print("[2] Sex Education")
print("[3] Game of Thrones")
print("[4] Dota")
print("[5] This is Us - 6ª temporada")

escolha = int(input("Digite o número correspondente à sua escolha: "))

if (escolha == 1):
    print("A série escolhida foi: Sandman")
elif (escolha) == 2:
    print("A série escolhida foi: Sex Education")
elif (escolha) == 3:
    print("A série escolhida foi: Game of Thrones")
elif (escolha) == 4:
    print("A série escolhida foi: Dota")
elif (escolha) == 5:
    print("A série escolhida foi: This is Us - 6ª temporada")
else:
    print("Opção inválida. Por favor, escolha um número entre 1 e 5")
